#  飞书
APP_ID: cli_axxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
BOT_NAME: Chat-GPT # 飞书机器人的名字
# openAI key
OPENAI_KEYS:  
 - sk-xxxxx
OPENAI_URL: https://api.openai.com
OPENAI_MODEL: gpt-3.5-turbo
# 服务器配置
HTTP_PORT: 9000
# 新人欢迎链接
WELCOME_LINK: https://www.baidu.com